### ISSUE TITLE
cloud_firestore_mocks failure upon FieldValue.serverTimestamp() and FieldValue.delete() 

### ISSUE THREAD

**Issue by suztomo** [atn832/firebase_auth_mocks#4]
Thank you for the great libraries. I really like the lightweight design that still gives good confidence on my implementation around Firestore.

While I tried to use the cloud_firestore_mocks, I found it does not work with ` FieldValue.serverTimestamp()` or `FieldValue.delete()`.

https://gist.github.com/suztomo/729ace09a54a32649dc2265631363649

```
    await subcollectionRef.document('foobar')
        .setData(<String, dynamic>{
      'content': 'MockFirestoreInstance is great',
      'createdBy': 'Tomo', 
      'created': FieldValue.serverTimestamp(), // type 'MethodChannelFieldValue' is not a subtype of type 'MockFieldValuePlatform' in type cast
    });
```

```
    await subcollectionRef.document('foobar')
        .setData(<String, dynamic>{
      'content': FieldValue.delete() // type 'MethodChannelFieldValue' is not a subtype of type 'MockFieldValuePlatform' in type cast
    });
```

# Error Message
```
FieldValue.serverTimestamp does not work:

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
type 'MethodChannelFieldValue' is not a subtype of type 'MockFieldValuePlatform' in type cast

When the exception was thrown, this was the stack:
#0      MockDocumentReference.updateData.<anonymous closure> (package:cloud_firestore_mocks/src/mock_document_reference.dart:34:74)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#2      MockDocumentReference.updateData (package:cloud_firestore_mocks/src/mock_document_reference.dart:32:10)
#3      MockDocumentReference.setData (package:cloud_firestore_mocks/src/mock_document_reference.dart:56:12)
#4      main.<anonymous closure> (file:///Users/suztomo/Documents/hitomemo/test/mock_firestore_test.dart:32:10)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The test description was:
  FieldValue.serverTimestamp does not work
════════════════════════════════════════════════════════════════════════════════════════════════════
ERROR: Test failed. See exception logs above.
The test description was: FieldValue.serverTimestamp does not work
```

For my use case of `FieldValue.serverTimestamp`, just replacing `FieldValue.serverTimestamp` with `DateTime.new()` resolves the problem, but it seems tough to replace `FieldValue.delete()`, which I would use to delete a field from a document.

I appreciate if the library can let me use `FieldValue.delete()`.

**Comment by suztomo** [comment]
I was not reading the [README](https://pub.dev/packages/cloud_firestore_mocks#-readme-tab-) to the end.

> delete document key/values with ValueField.delete(). If you use this feature, you first have to call MockFirestoreInstance.setupFieldValueFactory() in your unit tests.

```
    final fakeFirestore = MockFirestoreInstance()
    ..setupFieldValueFactory();
```

This resolved my problem.

**Comment by suztomo** [comment]
First of all, this was not correct repository.

**Comment by atn832** [comment]
I'm glad you find the library helpful!

I filed a ticket 2 weeks ago about supporting `FieldValue.serverTimestamp()` at https://github.com/atn832/cloud_firestore_mocks/issues/12. I might get to it eventually, but feel free to submit a PR!

Also I plan to set up the field value factory automatically when the MockFirestoreInstance instance is instantiated. It'll make things less confusing.

**Comment by suztomo** [comment]
> plan to set up the field value factory automatically

I guess it has a side effect (and you intentionally made optional to call the methof)? A better error message indicating the solution is also good.
